#!/bin/sh

#自动语言
uci set luci.main.lang=auto
uci commit luci

#自动挂载
uci set fstab.@global[0].anon_mount=1
uci commit fstab

#Argon 主题
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci

#时区设置
uci -q batch <<-EOF
	set system.@system[0].timezone='CST-8'
	set system.@system[0].zonename='Asia/Shanghai'
	delete system.ntp.server
	add_list system.ntp.server='time1.cloud.tencent.com'
	add_list system.ntp.server='ntp1.aliyun.com'
	add_list system.ntp.server='ntp.ntsc.ac.cn'
	add_list system.ntp.server='cn.ntp.org.cn'
EOF
uci commit system

#Feeds 更换镜像源
sed -i '/immortalwrt_core/d' /etc/opkg/distfeeds.conf
sed -i 's/downloads.openwrt.org/downloads.immortalwrt.cnsztl.eu.org/g' /etc/opkg/distfeeds.conf
#Add PubKey
wget -qO /etc/opkg/keys/8ead5420c4005b0d https://downloads.immortalwrt.cnsztl.eu.org/snapshots/key-build.pub

#使用bash替代ash
[ -f '/bin/bash' ] && sed -i 's|root:x:0:0:root:/root:/bin/ash|root:x:0:0:root:/root:/bin/bash|g' /etc/passwd

#uhttpd 设置
uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci commit uhttpd
/etc/init.d/uhttpd restart

#默认开启 Packet Steering
uci set network.globals.packet_steering='1'
uci commit network

#通用即插即用
uci set upnpd.config.igdv1='1'
uci set upnpd.config.enabled='1'
uci commit upnpd

#OpenClash 设置
echo "/etc/openclash/" >> /etc/sysupgrade.conf && cat /etc/sysupgrade.conf | sort | uniq > /tmp/tmp_sysupgrade_conf && cat /tmp/tmp_sysupgrade_conf > /etc/sysupgrade.conf

#dnsmasq 设置
uci set dhcp.@dnsmasq[0].rebind_protection='0'
uci commit dhcp
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

#计划任务
uci set system.@system[0].cronloglevel="9"
uci commit system
/etc/init.d/cron restart

#清理内存缓存
#sync; echo 3 > /proc/sys/vm/drop_caches

#system
ln -sf /sbin/ip /usr/bin/ip

#clean
rm -f /www/luci-static/resources/view/status/include/50_dsl.js
rm -f /www/luci-static/resources/view/status/include/70_ddns.js
rm -f /www/luci-static/resources/view/status/include/80_minidlna.js
rm -f /www/luci-static/resources/view/status/include/80_upnp.js

#清除 LuCI 残留缓存
rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache

exit 0